#!/usr/bin/env python3
"""Regenerate the repository's internal SHA-256 manifest."""

from __future__ import annotations

import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "manifests" / "FILES.sha256"
EXCLUDED_PARTS = {".git", "target", ".idea", ".vscode", "local-data", "__pycache__", ".venv", "do"}
EXCLUDED_FILES = {
    MANIFEST.resolve(),
    (ROOT / "AGENTS.md").resolve(),
    (ROOT / "CLAUDE.md").resolve(),
    (ROOT / ".env").resolve(),
}
EXCLUDED_SUFFIXES = {".pyc", ".pyo"}


def included_files() -> list[Path]:
    result: list[Path] = []
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        if any(part in EXCLUDED_PARTS for part in path.relative_to(ROOT).parts):
            continue
        if path.resolve() in EXCLUDED_FILES or path.suffix in EXCLUDED_SUFFIXES:
            continue
        result.append(path)
    return sorted(result, key=lambda value: value.relative_to(ROOT).as_posix())


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main() -> int:
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# SHA-256 manifest for the meshelf agent seed",
        "# Generated by scripts/refresh-manifest.py; the manifest file itself is excluded.",
    ]
    for path in included_files():
        relative = path.relative_to(ROOT).as_posix()
        lines.append(f"{sha256(path)}  {relative}")
    MANIFEST.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"Wrote {MANIFEST.relative_to(ROOT)} with {len(lines) - 2} entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
